[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /logs/cowrie.json
    Tag    cowrie
    Parser json
    Refresh_Interval 5

[OUTPUT]
    Name            http
    Match           cowrie
    Host            ${CLICKHOUSE_HOST}
    Port            ${CLICKHOUSE_PORT}
    tls             On
    tls.verify      Off
    URI             /?query=INSERT%20INTO%20logs.cowrie%20FORMAT%20JSONEachRow&input_format_skip_unknown_fields=1
    Header          X-ClickHouse-User ${CLICKHOUSE_USER}
    Header          X-ClickHouse-Key  ${CLICKHOUSE_PASSWORD}
    Format          json_stream
