apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true

    url: https://clickhouse:8443

    jsonData:
      defaultDatabase: logs
      server: clickhouse
      port: 8443
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: true
      secure: true

    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
