[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224
    Tag     beelzebub

[FILTER]
    Name         parser
    Match        beelzebub
    Key_Name     log
    Parser       json
    Reserve_Data On

[FILTER]
    Name          nest
    Match         beelzebub
    Operation     lift
    Nested_under  event

[OUTPUT]
    Name            http
    Match           beelzebub
    Host            139.59.112.240
    Port            8123
    URI             /?query=INSERT%20INTO%20logs.beelzebub%20FORMAT%20JSONEachRow&input_format_skip_unknown_fields=1&date_time_input_format=best_effort
    Header          X-ClickHouse-User default_user
    Header          X-ClickHouse-Key  default_password
    Format          json_stream
